### PR TITLE
Adding Symfony4 support

### PR DESCRIPTION
**Pull request by webcome**
I changed two file for Symfony4 support on #SymfonyConHackday2017

### CODE REVIEW

**Comment by Nyholm** [comment]
Awesome!

**Comment by honzagula** [comment]
Voting for merge! Thank you!

**Review by rippergun — APPROVED** [review]

**Comment by Nyholm** [comment]
Friendly ping to @cleentfaar

**Comment by olix21** [comment]
Is this library still active? Can we merge this PR? Symfony 4 support could be great!

**Comment by Nyholm** [comment]
Wohoo!

**Comment by cleentfaar** [comment]
Merged for what it's worth. Sorry guys obviously this repo is no longer maintained 😢, I will archive it to reflect this.

**Pull request merged**
