### PR TITLE
Updated cleentfaar/slack required version

### PR DESCRIPTION
**Pull request by nunojsferreira**
Updating this dependency fixes the issue #15 

And most important, updates guzzle dependency for last version 6.

### CODE REVIEW

**Comment by nunojsferreira** [comment]
Seems like Guzzle6 is not compatible with PHP5.4 so this breaks the build for that version. How do you guys handle this?

https://github.com/guzzle/guzzle/blob/master/composer.json

**Comment by ryzy** [comment]
Can we do sth about it? Otherwise it's bit troublesome.

For now the workaround is to put 
```
"cleentfaar/slack": "0.18.1 as 0.15.3",
```
in your composer.json

**Comment by cleentfaar** [comment]
I'm currently catching up with a PR that will fix this issue: https://github.com/cleentfaar/CLSlackBundle/pull/20. The minimal PHP version from now on will be 5.5. Sorry for the long wait and thanks for your efforts!

**Comment by cleentfaar** [comment]
The issue has been fixed now with the release of version 0.20.1 (link: https://github.com/cleentfaar/CLSlackBundle/releases/tag/0.20.1)

Thanks for your patience and be sure to report any problems you may have with the update.

**Pull request closed without merging**
